import time
time.sleep(0.05)
print("\nHIPAA - Help In Protecting All Ailments (Healthcare)")
time.sleep(0.05)
print("\nFERPA - Files of Every Report & Pupil's Academics (Education Records)")
time.sleep(0.05)
print("\nCOPPA - Cops On Patrol Protecting Adolescents (Children)")
time.sleep(0.05)
print("\nPCI - Plastic Card Insurance (European Union)")
time.sleep(0.05)
print("\nGDPR - Giant Data Protection Rule (Markets & Platforms)")
time.sleep(0.05)
print("\nCISPA - Cyber Info Shared to Prevent Attacks (Cybersecurity)")
time.sleep(0.05)
print("\nData Brokers - Collect and sell personal data")
time.sleep(0.05)
quit_ =  input("\nType anything to exit: ")

