import turtle
turtle.getscreen()
turtle.hideturtle()
turtle.bgcolor("navy")
turtle.title("Solar System")
turtle.penup()
turtle.left(180)
turtle.forward(120)
turtle.left(180)

turtle.pencolor("yellow")
turtle.fillcolor("yellow")
turtle.begin_fill()
turtle.pendown()
turtle.circle(40)
turtle.end_fill()
turtle.penup()

turtle.forward(55)

turtle.pencolor("brown")
turtle.fillcolor("brown")
turtle.begin_fill()
turtle.pendown()
turtle.circle(3)
turtle.end_fill()
turtle.penup()

turtle.forward(30)

turtle.pencolor("grey")
turtle.fillcolor("grey")
turtle.begin_fill()
turtle.pendown()
turtle.circle(5)
turtle.end_fill()
turtle.penup()

turtle.forward(30)

turtle.pencolor("lime")
turtle.fillcolor("lime")
turtle.begin_fill()
turtle.pendown()
turtle.circle(8)
turtle.end_fill()
turtle.penup()

turtle.forward(30)

turtle.pencolor("red")
turtle.fillcolor("red")
turtle.begin_fill()
turtle.pendown()
turtle.circle(5)
turtle.end_fill()
turtle.penup()

turtle.forward(30)

turtle.pencolor("orange")
turtle.fillcolor("orange")
turtle.begin_fill()
turtle.pendown()
turtle.circle(15)
turtle.end_fill()
turtle.penup()

turtle.forward(35)

turtle.pencolor("yellow")
turtle.fillcolor("yellow")
turtle.begin_fill()
turtle.pendown()
turtle.circle(10)
turtle.end_fill()
turtle.penup()

turtle.forward(30)

turtle.pencolor("lightblue")
turtle.fillcolor("lightblue")
turtle.begin_fill()
turtle.pendown()
turtle.circle(8)
turtle.end_fill()
turtle.penup()

turtle.forward(30)

turtle.pencolor("purple")
turtle.fillcolor("purple")
turtle.begin_fill()
turtle.pendown()
turtle.circle(8)
turtle.end_fill()
turtle.penup()
